[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false 